export const REVENUE_PROJECTIONS : string = "Revenue Projections";
export const COST_PROJECTIONS : string = "Cost Projections";
export const PROFIT_PROJECTIONS : string = "Profit Projections";
export const RESOURCES_RELEASES : string = "Resources & Releases";

export const REVENUE_PROJECTIONS_DETAIL : string[] = ["Recurring: Input of the incremental recurring revenue projections. \n(eg. Maintenance, Subscription, SaaS, Rental, ...)",
                                                    "Non-Recurring: Input of the incremental non-recurring revenue projections. \n(eg. Perpetual Licenses, Hardware Systems, ...)",
                                                    "Historical CAGR: Input of the historical typical growth rate in case of an update to an existing product. (5 years where available)",
                                                    "Estimated CAGR: Automated calculation for 5 years CAGR. This is the average growth over the 5 year  growth captured in this project."];
export const COST_PROJECTIONS_DETAIL : string[] = ["Cost of Sales: Input of the cost of sales related to the project. \n(eg. Hosting costs, Royalty payments, Direct Material or Labor, ...)",
                                                    "OPEX: Input of all other costs that are not directly linked to the Sales. \n(eg. R&D costs, Marketing, incremental Sales, Service , IT costs directly related to the launch, and other costs relevant to the project)",
                                                    "Investment Pre-Launch: Same as in OPEX, however pre-launch. \n(eg. R&D efforts before launch)",
                                                    "Recurring Investment: Calculation of the average yearly OPEX spend after launch."];
export const PROFIT_PROJECTIONS_DETAIL : string[] = ["NPV: Net present value is the difference between the present value of cash inflows and the present value of cash outflows over a period of time.",
                                                    "5 Year Ebit: The sum of the profit flowing out of the project over the 5 year period.",
                                                    "Current Gross Profit: Variable margin that is generated by the Business Goal. It serves as the contribution of the sales to further cover the investments. \nFormula: (Sales – Cost of Sales)/Sales",
                                                    "Gross Profit Improvement: We expect the Gross profit to improve over the years. This metric measures the improvement.",
                                                    "Simple Payback: Calculation of the time required until all pre-launch investments are covered."];
export const RESOURCES_RELEASES_DETAIL : string[] = ["Estimated FTE Count: Estimation on R&D count.",
                                                    "Runways: Runways required to execute the Business Goal. This has an impact on the RRM.",
                                                    "Estimated Development Time: Indication on duration of the Business Goal, given that the FTE count is allocated.",
                                                    "Products: Products that will be affected by the Business Goal."];
